config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :comments
  end 
  # get "/projects/:user_id", to: "projects#index", as: "index"
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user 
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord

  has_many :projects, dependent: :destroy
  has_many :comments, through: :projects
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

         def configure_permitted_parameters
              devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:user_name, :email, :password)}

              devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:user_name, :email, :password, :current_password)}
         end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  
    def create
      @comment = Project.find(params[:project_id]).comments.new(comment_params)
      if @comment.save 
        redirect_to project_path(params[:project_id])
      else 
        redirect_to new_project_commment_path(params[:project_id])
      end
    end
  
    def edit
      @comment = current_user.comments.find(params[:id])
        ##{name:"xxx"}
    end

    def update
      @comment = current_user.comments.find(params[:id])
      ##{name:"yyy"}
      @comment.update(comment_params)
      redirect_to project_path(@comment) 
    end
  
    def destroy
      @comment = current_user.comments.find(params[:id])
      @comment.destroy
      redirect_to projects_path
    end
  
    private
  
      def comment_params
        params.require(:comment).permit(:body)
      end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
    @users = User.all
   end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    # before_action :set_project, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:edit, :update, :destroy, :create, :new]
  
    def index
      @projects = Project.all
      
     
    end
  
    def show
      @project = Project.find(params[:id])
      @comment = Project.find(params[:id]).comments.new
    end
  
    def new
      @project = current_user.projects.new
    end

    def create
      @project = current_user.projects.new(project_params)
      if @project.save 
        redirect_to project_path(@project)
      else 
        redirect_to new_project_path
      end
    end
  
    def edit
     @project = current_user.projects.find(params[:id])
        ##{name:"xxx"}
    end

    def update
      @project = current_user.projects.find(params[:id])
      ##{name:"yyy"}
      @project.update(project_params)
      redirect_to project_path(@project) 
    end
  
    def destroy
      @project = current_user.projects.find(params[:id])
      @project.destroy
      redirect_to projects_path
    end
  
    private
      # def set_project
      #   @project = Project.find(params[:id])
      # end
  
      def project_params
        params.require(:project).permit(:name, :description, :contactinfo)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
    <p id="notice"><%= notice %></p>
<div class="center">
<h1>All Projects</h1>
        <br>
         <br>
        </div>
        <div class="maincontent">
        <div class="d-flex flex-wrap">
          <% @users.each do |user|%> 
          
        <div class="card">
          <div class="card-body">
          <h4 class="card-title">
       <%= user.user_name%></h4>

        <%= link_to ' Projects', projects_path , :class=>"btn btn-dark" %> 
              </div>
       </div>
       <br>
    <% end %>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://fonts.googleapis.com/css?family=Caveat|Permanent+Marker&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito|Permanent+Marker&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Bebas+Neue&display=swap" rel="stylesheet">
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Project</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <link href="https://fonts.googleapis.com/css?family=Caveat|Permanent+Marker|Source+Serif+Pro&display=swap" rel="stylesheet">
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>


  <div class="header">
   
      <% if (user_signed_in?) %>
      <span id="welcome"> Welcome  <%= current_user.user_name %></span>
      <ul class="nav">
     <li class="nav-item"> <%= link_to 'Sign Out', destroy_user_session_path, method: :delete , :class=>"nav-link"%><li>
     <li class="nav-item"> <%= link_to 'Edit user', edit_user_registration_path, method: :get, :class=>"nav-link" %> </li>

      <% else %>
      <%= link_to 'Sign In', new_user_session_path, method: :get, :id=>"signout" %>
      <%end%>
      
</ul>
</div>
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p> 


    <%= yield %>
  
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>

    <div class="field">
      <%= form.label :contactinfo %>
      <%= form.text_field :contactinfo %>
    </div>

  
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/projects/edit.html.erb
<div class= "center">
<div class= "new">
<h1>Edit Project</h1>
<%= form_for @project, url: {action: "update"} do |form|%>
<%= form.label :name%>
    <br>
    <%= form.text_field :name%>
  <br>
  <br>
    <%= form.label :description%>
    <br>
    <%=form.text_area :description , size: "50x 10"%>
<br>
    <%= form.label :contactinfo%>
    <br>
    <%= form.text_field :contactinfo %>
<br>
<br>
<%= form.submit "edit" , :class=>"btn btn-dark"%>
<%end%>
<br>
<%= link_to 'Back', projects_path , :class=>"btn btn-dark"%>
</div> </div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="center">
<h1>All Projects</h1>

    <% User.all.each do |user| %>
     
      
         <br>
       
        </div>
        <div class="maincontent">
        <div class="d-flex flex-wrap">
          <% user.projects.each do |project|%> 
          
        <div class="card">
          <div class="card-body">
          <h4 class="card-title">
       <%= project.name%></h4>

        <%= link_to 'Show', project_path(project), :class=>"btn btn-dark"%>
              </div>
       </div>
       <br>
              <%end%>
    <% end %>
     <%= link_to 'Add New project', new_project_path, :class=>"btn btn-dark" %>
       
</div>
</div>

app/views/projects/new.html.erb
<div class="center">
<div class= "new">
<h2> Add New Project</h2>
<%= form_for  @project, url: {action: "create"} do |form| %>
    <%= form.label :name%>
    <br>
    <%= form.text_field :name%>
  <br>
  <br>
    <%= form.label :description%>
    <br>
    <%=form.text_area :description , size: "50x 10"%>
<br>
    <%= form.label :contactinfo%>
    <br>
    <%= form.text_field :contactinfo %>
<br>
<br>
    <%= form.submit "Save" , :class=>"btn btn-dark"%>
<%end%>

<%# render 'form', project: @project %>
<br>
<%= link_to 'Back', projects_path, :class=>"btn btn-dark" %>
</div>
</div>

app/views/projects/show.html.erb
<div class="show">
<p>
  <strong>Project Name:</strong>
  <%= @project.name %>
</p>
<p>
  <strong>Modified by: </strong> <%= @project.user.user_name %> </p>
<p>
  <strong>Contact Information:</strong>
  <%= @project.contactinfo %>
</p>
<p>
<hr>
  <strong>Description:</strong>
  <%= @project.description %>
</p>
<hr>
<p>
<strong>Comments:</strong>
</p>
<% @project.comments.each do |comment|%>
<p><%= comment.body%></p>
<%end%>
<hr>

<%= form_for @comment, :url => project_comments_path(@project) do |f| %>

  <%= f.label :comment , "Do you have any comment?"%>
   <br>

  <%= f.text_area :body , size:"50 x 3" , :id=>"tarea"%>
  <br>
  <%= f.submit "Submit", :class=>"btn btn-dark"%>
<br>
<% end %>
<br>

<%= link_to 'Edit', edit_project_path(@project), :class=>"btn btn-dark" %> 
<%= link_to 'Back', projects_path, :class=>"btn btn-dark" %> 
<td><%= link_to 'Delete Project', project_path(@project), method: :DELETE, data: { confirm: 'Are you sure?' }, :class=>"btn btn-dark" %></td>
</div>